name: Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.16.0'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Run lint
        run: yarn build

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.16.0'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Run lint
        run: yarn lint

  unit-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.16.0'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Unit tests
        run: yarn test

  e2e-test:
    needs: unit-test
    runs-on: ubuntu-latest
    env:
      WORKERS: 2
      REPORT_DIR: 'cypress/reports'
      POLL: 'false'
      WEIGHT_PER_TEST: 1
      BASE_WEIGHT: 1
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.16.0'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Run Cypress tests in parallel (POLL=false)
        run: yarn test:e2e

      - name: Generate report (POLL=false)
        run: yarn cy:report

  e2e-test_poll:
    needs: unit-test
    runs-on: ubuntu-latest
    env:
      WORKERS: 2
      REPORT_DIR: 'cypress/reports'
      POLL: 'true'
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.16.0'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Run Cypress tests in parallel (POLL=true)
        run: yarn test:e2e

      - name: Generate report (POLL=true)
        run: yarn cy:report
